"""Owner account contract; no generic provider proxy or decrypt endpoint."""
ACCOUNTS = "/settings/accounts/google"
ACCOUNTS_CALLBACK = ACCOUNTS + "/callback"
SERVICE_HEADER = "X-Reachy-Service-Token"
BINDING_COOKIE = "reachy_google_binding"
CONFIGURE = ACCOUNTS + "/configure"
CONNECT = ACCOUNTS + "/connect"
COMPLETE = ACCOUNTS + "/complete"
TEST = ACCOUNTS + "/test"
DISCONNECT = ACCOUNTS + "/disconnect"
CALENDARS = ACCOUNTS + "/calendars"
SELECTION = ACCOUNTS + "/selection"
EVENTS = ACCOUNTS + "/events"
MESSAGES = ACCOUNTS + "/messages"
MESSAGE = ACCOUNTS + "/messages/{message_id}"
FREE_BUSY = ACCOUNTS + "/free-busy"
