"""Operator routes shared by the hub proxy and core service."""

LLM_SETTINGS = "/settings/llm"
LLM_USAGE = "/llm/usage"
PERSONA_SETTINGS = "/settings/persona"
WEBSEARCH_SETTINGS = "/settings/websearch"
# Phase 24d: in-memory owner debug view of recent searches.
WEBSEARCH_LOG = "/websearch/log"
STATUS = "/status"
AUTH_LOGIN = "/auth/login"
AUTH_LOGOUT = "/auth/logout"
AUTH_ME = "/auth/me"
ROBOTS = "/robots"
ROBOTS_STANDBY = "/robots/standby"
ROBOTS_RESUME = "/robots/resume"
# Phase 24c (ADR 0023): owner controls for robot microphone conversation.
ROBOT_VOICE = "/robot-voice"
ROBOT_VOICE_START = "/robot-voice/start"
ROBOT_VOICE_RENEW = "/robot-voice/renew"
ROBOT_VOICE_STOP = "/robot-voice/stop"
